/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-08 at 09:34:25 UTC 
 * Modify at your own risk.
 */

package spelleritus_superuser.woordpakketapi;

import spelleritus_superuser.woordpakketapi.model.CollectionResponseWoordpakket;
import spelleritus_superuser.woordpakketapi.model.Woordpakket;

/**
 * Service definition for Woordpakketapi (v3).
 *
 * <p>
 * Een API om woordpakketten te beheren
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href= target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link WoordpakketapiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Woordpakketapi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the woordpakketapi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://spelleritus-superuser.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "woordpakketapi/v3/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Woordpakketapi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Woordpakketapi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getwpbyid".
   *
   * This request holds the parameters needed by the woordpakketapi server.  After setting any
   * optional parameters, call the {@link Getwpbyid#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public Getwpbyid getwpbyid(java.lang.Long id) throws java.io.IOException {
    Getwpbyid result = new Getwpbyid(id);
    initialize(result);
    return result;
  }

  public class Getwpbyid extends WoordpakketapiRequest<Woordpakket> {

    private static final String REST_PATH = "woordpakketapi/getwpbyid";

    /**
     * Create a request for the method "getwpbyid".
     *
     * This request holds the parameters needed by the the woordpakketapi server.  After setting any
     * optional parameters, call the {@link Getwpbyid#execute()} method to invoke the remote
     * operation. <p> {@link
     * Getwpbyid#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected Getwpbyid(java.lang.Long id) {
      super(Woordpakketapi.this, "GET", REST_PATH, null, Woordpakket.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Getwpbyid setAlt(java.lang.String alt) {
      return (Getwpbyid) super.setAlt(alt);
    }

    @Override
    public Getwpbyid setFields(java.lang.String fields) {
      return (Getwpbyid) super.setFields(fields);
    }

    @Override
    public Getwpbyid setKey(java.lang.String key) {
      return (Getwpbyid) super.setKey(key);
    }

    @Override
    public Getwpbyid setOauthToken(java.lang.String oauthToken) {
      return (Getwpbyid) super.setOauthToken(oauthToken);
    }

    @Override
    public Getwpbyid setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Getwpbyid) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Getwpbyid setQuotaUser(java.lang.String quotaUser) {
      return (Getwpbyid) super.setQuotaUser(quotaUser);
    }

    @Override
    public Getwpbyid setUserIp(java.lang.String userIp) {
      return (Getwpbyid) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public Getwpbyid setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public Getwpbyid set(String parameterName, Object value) {
      return (Getwpbyid) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getwpbyuserid".
   *
   * This request holds the parameters needed by the woordpakketapi server.  After setting any
   * optional parameters, call the {@link Getwpbyuserid#execute()} method to invoke the remote
   * operation.
   *
   * @param userid
   * @return the request
   */
  public Getwpbyuserid getwpbyuserid(java.lang.Integer userid) throws java.io.IOException {
    Getwpbyuserid result = new Getwpbyuserid(userid);
    initialize(result);
    return result;
  }

  public class Getwpbyuserid extends WoordpakketapiRequest<Woordpakket> {

    private static final String REST_PATH = "woordpakketapi/getwpbyuserid";

    /**
     * Create a request for the method "getwpbyuserid".
     *
     * This request holds the parameters needed by the the woordpakketapi server.  After setting any
     * optional parameters, call the {@link Getwpbyuserid#execute()} method to invoke the remote
     * operation. <p> {@link Getwpbyuserid#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param userid
     * @since 1.13
     */
    protected Getwpbyuserid(java.lang.Integer userid) {
      super(Woordpakketapi.this, "GET", REST_PATH, null, Woordpakket.class);
      this.userid = com.google.api.client.util.Preconditions.checkNotNull(userid, "Required parameter userid must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Getwpbyuserid setAlt(java.lang.String alt) {
      return (Getwpbyuserid) super.setAlt(alt);
    }

    @Override
    public Getwpbyuserid setFields(java.lang.String fields) {
      return (Getwpbyuserid) super.setFields(fields);
    }

    @Override
    public Getwpbyuserid setKey(java.lang.String key) {
      return (Getwpbyuserid) super.setKey(key);
    }

    @Override
    public Getwpbyuserid setOauthToken(java.lang.String oauthToken) {
      return (Getwpbyuserid) super.setOauthToken(oauthToken);
    }

    @Override
    public Getwpbyuserid setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Getwpbyuserid) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Getwpbyuserid setQuotaUser(java.lang.String quotaUser) {
      return (Getwpbyuserid) super.setQuotaUser(quotaUser);
    }

    @Override
    public Getwpbyuserid setUserIp(java.lang.String userIp) {
      return (Getwpbyuserid) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer userid;

    /**

     */
    public java.lang.Integer getUserid() {
      return userid;
    }

    public Getwpbyuserid setUserid(java.lang.Integer userid) {
      this.userid = userid;
      return this;
    }

    @Override
    public Getwpbyuserid set(String parameterName, Object value) {
      return (Getwpbyuserid) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertwoordpakket".
   *
   * This request holds the parameters needed by the woordpakketapi server.  After setting any
   * optional parameters, call the {@link Insertwoordpakket#execute()} method to invoke the remote
   * operation.
   *
   * @param contents
   * @param identifier
   * @return the request
   */
  public Insertwoordpakket insertwoordpakket(java.lang.String contents, java.lang.String identifier) throws java.io.IOException {
    Insertwoordpakket result = new Insertwoordpakket(contents, identifier);
    initialize(result);
    return result;
  }

  public class Insertwoordpakket extends WoordpakketapiRequest<Woordpakket> {

    private static final String REST_PATH = "woordpakketapi/addwoordpakket";

    /**
     * Create a request for the method "insertwoordpakket".
     *
     * This request holds the parameters needed by the the woordpakketapi server.  After setting any
     * optional parameters, call the {@link Insertwoordpakket#execute()} method to invoke the remote
     * operation. <p> {@link Insertwoordpakket#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param contents
     * @param identifier
     * @since 1.13
     */
    protected Insertwoordpakket(java.lang.String contents, java.lang.String identifier) {
      super(Woordpakketapi.this, "POST", REST_PATH, null, Woordpakket.class);
      this.contents = com.google.api.client.util.Preconditions.checkNotNull(contents, "Required parameter contents must be specified.");
      this.identifier = com.google.api.client.util.Preconditions.checkNotNull(identifier, "Required parameter identifier must be specified.");
    }

    @Override
    public Insertwoordpakket setAlt(java.lang.String alt) {
      return (Insertwoordpakket) super.setAlt(alt);
    }

    @Override
    public Insertwoordpakket setFields(java.lang.String fields) {
      return (Insertwoordpakket) super.setFields(fields);
    }

    @Override
    public Insertwoordpakket setKey(java.lang.String key) {
      return (Insertwoordpakket) super.setKey(key);
    }

    @Override
    public Insertwoordpakket setOauthToken(java.lang.String oauthToken) {
      return (Insertwoordpakket) super.setOauthToken(oauthToken);
    }

    @Override
    public Insertwoordpakket setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Insertwoordpakket) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Insertwoordpakket setQuotaUser(java.lang.String quotaUser) {
      return (Insertwoordpakket) super.setQuotaUser(quotaUser);
    }

    @Override
    public Insertwoordpakket setUserIp(java.lang.String userIp) {
      return (Insertwoordpakket) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String contents;

    /**

     */
    public java.lang.String getContents() {
      return contents;
    }

    public Insertwoordpakket setContents(java.lang.String contents) {
      this.contents = contents;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String identifier;

    /**

     */
    public java.lang.String getIdentifier() {
      return identifier;
    }

    public Insertwoordpakket setIdentifier(java.lang.String identifier) {
      this.identifier = identifier;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String description;

    /**

     */
    public java.lang.String getDescription() {
      return description;
    }

    public Insertwoordpakket setDescription(java.lang.String description) {
      this.description = description;
      return this;
    }

    @Override
    public Insertwoordpakket set(String parameterName, Object value) {
      return (Insertwoordpakket) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listwoordpakketten".
   *
   * This request holds the parameters needed by the woordpakketapi server.  After setting any
   * optional parameters, call the {@link Listwoordpakketten#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public Listwoordpakketten listwoordpakketten() throws java.io.IOException {
    Listwoordpakketten result = new Listwoordpakketten();
    initialize(result);
    return result;
  }

  public class Listwoordpakketten extends WoordpakketapiRequest<CollectionResponseWoordpakket> {

    private static final String REST_PATH = "woordpakketapi/listwoordpakketten";

    /**
     * Create a request for the method "listwoordpakketten".
     *
     * This request holds the parameters needed by the the woordpakketapi server.  After setting any
     * optional parameters, call the {@link Listwoordpakketten#execute()} method to invoke the remote
     * operation. <p> {@link Listwoordpakketten#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected Listwoordpakketten() {
      super(Woordpakketapi.this, "GET", REST_PATH, null, CollectionResponseWoordpakket.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Listwoordpakketten setAlt(java.lang.String alt) {
      return (Listwoordpakketten) super.setAlt(alt);
    }

    @Override
    public Listwoordpakketten setFields(java.lang.String fields) {
      return (Listwoordpakketten) super.setFields(fields);
    }

    @Override
    public Listwoordpakketten setKey(java.lang.String key) {
      return (Listwoordpakketten) super.setKey(key);
    }

    @Override
    public Listwoordpakketten setOauthToken(java.lang.String oauthToken) {
      return (Listwoordpakketten) super.setOauthToken(oauthToken);
    }

    @Override
    public Listwoordpakketten setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Listwoordpakketten) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Listwoordpakketten setQuotaUser(java.lang.String quotaUser) {
      return (Listwoordpakketten) super.setQuotaUser(quotaUser);
    }

    @Override
    public Listwoordpakketten setUserIp(java.lang.String userIp) {
      return (Listwoordpakketten) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public Listwoordpakketten setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public Listwoordpakketten setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public Listwoordpakketten set(String parameterName, Object value) {
      return (Listwoordpakketten) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "searchwoordpakketen".
   *
   * This request holds the parameters needed by the woordpakketapi server.  After setting any
   * optional parameters, call the {@link Searchwoordpakketen#execute()} method to invoke the remote
   * operation.
   *
   * @param searchterm
   * @return the request
   */
  public Searchwoordpakketen searchwoordpakketen(java.lang.String searchterm) throws java.io.IOException {
    Searchwoordpakketen result = new Searchwoordpakketen(searchterm);
    initialize(result);
    return result;
  }

  public class Searchwoordpakketen extends WoordpakketapiRequest<CollectionResponseWoordpakket> {

    private static final String REST_PATH = "woordpakketapi/listwoordpakketten";

    /**
     * Create a request for the method "searchwoordpakketen".
     *
     * This request holds the parameters needed by the the woordpakketapi server.  After setting any
     * optional parameters, call the {@link Searchwoordpakketen#execute()} method to invoke the remote
     * operation. <p> {@link Searchwoordpakketen#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param searchterm
     * @since 1.13
     */
    protected Searchwoordpakketen(java.lang.String searchterm) {
      super(Woordpakketapi.this, "POST", REST_PATH, null, CollectionResponseWoordpakket.class);
      this.searchterm = com.google.api.client.util.Preconditions.checkNotNull(searchterm, "Required parameter searchterm must be specified.");
    }

    @Override
    public Searchwoordpakketen setAlt(java.lang.String alt) {
      return (Searchwoordpakketen) super.setAlt(alt);
    }

    @Override
    public Searchwoordpakketen setFields(java.lang.String fields) {
      return (Searchwoordpakketen) super.setFields(fields);
    }

    @Override
    public Searchwoordpakketen setKey(java.lang.String key) {
      return (Searchwoordpakketen) super.setKey(key);
    }

    @Override
    public Searchwoordpakketen setOauthToken(java.lang.String oauthToken) {
      return (Searchwoordpakketen) super.setOauthToken(oauthToken);
    }

    @Override
    public Searchwoordpakketen setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Searchwoordpakketen) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Searchwoordpakketen setQuotaUser(java.lang.String quotaUser) {
      return (Searchwoordpakketen) super.setQuotaUser(quotaUser);
    }

    @Override
    public Searchwoordpakketen setUserIp(java.lang.String userIp) {
      return (Searchwoordpakketen) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String searchterm;

    /**

     */
    public java.lang.String getSearchterm() {
      return searchterm;
    }

    public Searchwoordpakketen setSearchterm(java.lang.String searchterm) {
      this.searchterm = searchterm;
      return this;
    }

    @Override
    public Searchwoordpakketen set(String parameterName, Object value) {
      return (Searchwoordpakketen) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatewoordpakket".
   *
   * This request holds the parameters needed by the woordpakketapi server.  After setting any
   * optional parameters, call the {@link Updatewoordpakket#execute()} method to invoke the remote
   * operation.
   *
   * @param emailsuperuser
   * @param content the {@link com.appspot.Woordpakket}
   * @return the request
   */
  public Updatewoordpakket updatewoordpakket(java.lang.String emailsuperuser, Woordpakket content) throws java.io.IOException {
    Updatewoordpakket result = new Updatewoordpakket(emailsuperuser, content);
    initialize(result);
    return result;
  }

  public class Updatewoordpakket extends WoordpakketapiRequest<Void> {

    private static final String REST_PATH = "void/{emailsuperuser}";

    /**
     * Create a request for the method "updatewoordpakket".
     *
     * This request holds the parameters needed by the the woordpakketapi server.  After setting any
     * optional parameters, call the {@link Updatewoordpakket#execute()} method to invoke the remote
     * operation. <p> {@link Updatewoordpakket#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param emailsuperuser
     * @param content the {@link Woordpakket}
     * @since 1.13
     */
    protected Updatewoordpakket(java.lang.String emailsuperuser, Woordpakket content) {
      super(Woordpakketapi.this, "PUT", REST_PATH, content, Void.class);
      this.emailsuperuser = com.google.api.client.util.Preconditions.checkNotNull(emailsuperuser, "Required parameter emailsuperuser must be specified.");
    }

    @Override
    public Updatewoordpakket setAlt(java.lang.String alt) {
      return (Updatewoordpakket) super.setAlt(alt);
    }

    @Override
    public Updatewoordpakket setFields(java.lang.String fields) {
      return (Updatewoordpakket) super.setFields(fields);
    }

    @Override
    public Updatewoordpakket setKey(java.lang.String key) {
      return (Updatewoordpakket) super.setKey(key);
    }

    @Override
    public Updatewoordpakket setOauthToken(java.lang.String oauthToken) {
      return (Updatewoordpakket) super.setOauthToken(oauthToken);
    }

    @Override
    public Updatewoordpakket setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Updatewoordpakket) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Updatewoordpakket setQuotaUser(java.lang.String quotaUser) {
      return (Updatewoordpakket) super.setQuotaUser(quotaUser);
    }

    @Override
    public Updatewoordpakket setUserIp(java.lang.String userIp) {
      return (Updatewoordpakket) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String emailsuperuser;

    /**

     */
    public java.lang.String getEmailsuperuser() {
      return emailsuperuser;
    }

    public Updatewoordpakket setEmailsuperuser(java.lang.String emailsuperuser) {
      this.emailsuperuser = emailsuperuser;
      return this;
    }

    @Override
    public Updatewoordpakket set(String parameterName, Object value) {
      return (Updatewoordpakket) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Woordpakketapi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Woordpakketapi}. */
    @Override
    public Woordpakketapi build() {
      return new Woordpakketapi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link WoordpakketapiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setWoordpakketapiRequestInitializer(
        WoordpakketapiRequestInitializer woordpakketapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(woordpakketapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
